### ISSUE TITLE
[P1][Architecture] Implement a deterministic one-command rebuild through selected ports

### ISSUE THREAD

**Issue by Illuminfti** [Illuminfti/kizuki#103]
# [P1][Architecture] Implement a deterministic one-command rebuild through selected ports

**Audit finding:** KZ-029  
**Snapshot:** `870ccdca1c487d5dbebdabfa08b961d8a6a4c824`  
**Area:** Architecture  
**Severity:** P1  
**Suggested labels:** `severity:p1, architecture`

## Evidence

`packages/core/src/derived.ts; packages/cli/src/commands`

A library rebuild function exists for hard-coded search/graph, but there is no kizuki rebuild command, claims stream, selected port, vector/entities layers, generation metadata, or equivalence test.

## Why this matters under RFC 0002

Invariant 2 requires observable derived state to be reproducible from ledger plus canon with one command.

## Proposed fix

Implement rebuild --layer/--port/--prune-old, stream rather than materialize, build in a new generation, verify golden recall/document sets, atomically switch, and record engine.json/port_state.

## Scope guard

Audit and remediation must remain pinned to `870ccdca1c487d5dbebdabfa08b961d8a6a4c824` when reproducing this finding. Rebase the fix onto the current `main` only after confirming the defect still exists. Do not add an owner-review or promotion queue as the remedy.

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/613 records FTS `rebuilt_at` in the store transaction and repairs `engine.json` on reopen. Tests: `bun test` fts5/rebuild/cli rebuild/derived-equivalence; `tsc --noEmit`. Does not close #103 (selected-layer/port/prune-old rebuild flags remain unbuilt).

**Comment by Illuminfti** [comment]
Reopened. PR #613 recorded FTS rebuilt_at only. Remaining rebuild flags (--layer/--port/--prune-old) are unbuilt.

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/621.

Adds `rebuild --layer graph` for the SQLite graph floor and skips search refresh. Proof: `bun test packages/core/test/retrieval/rebuild.test.ts packages/cli/test/rebuild.test.ts`. Selected-port rebuild and prune-old remain unbuilt.

Refs #103

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/629.

Adds `rebuild --prune-old` to erase inactive owned retrieval generations and keep the bound engine or SQLite floor. Proof: `bun test packages/cli/test/rebuild.test.ts packages/cli/test/owned-retrieval-inventory.test.ts`. `--port` remains refused.

Refs #103

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/636.

`rebuild --port ID` names the bound store and refuses any other id. It does not switch engines. Proof: `bun test packages/cli/test/rebuild.test.ts`.

Refs #103

**Comment by Illuminfti** [comment]
Slice shipped in PR https://github.com/Illuminfti/kizuki/pull/664.

`rebuild --port ID` binds the named installed engine for that invocation through `openConfiguredRetrieval`. It does not rewrite `serve.toml`. Unknown IDs and a busy engine fail closed. Retry after a successful unbound rebuild proves handle cleanup.

Tests: `bun test packages/cli/test/rebuild.test.ts packages/core/test/retrieval/rebuild.test.ts` and `bun x tsc --noEmit`.

Remaining: persistent default switch, generation metadata beyond the current report, golden recall/document sets.

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/672.

Repeated `rebuild --port kizuki.retrieval.embedded-pg` and reopen preserve fixture-defined lexical event recall for `grace` (Ada+Grace), `library`, and `linus`. Authoritative event/claim/receipt rows stay unchanged. `serve.toml` is not rewritten.

Tests: `bun test packages/cli/test/rebuild.test.ts` and `bun x tsc --noEmit`.

Remaining: persistent default switch.

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/725

Documents that `rebuild --port ID` selects an installed engine for this invocation and does not rewrite `serve.toml`. Replaces the stale bound-only docs contract.

Tests: `bun test packages/core/test/retrieval/rebuild-port-docs.test.ts packages/cli/test/help.test.ts packages/cli/test/inventory.test.ts`

Does not close #103. Persistent default switch remains unbuilt.

**Comment by Illuminfti** [comment]
Tick12 slice: `rebuild --layer search` restores the SQLite lexical floor without touching graph or rewriting serve.toml.

PR: https://github.com/Illuminfti/kizuki/pull/810
Does not close this issue. Persistent default switch remains unbuilt.

**Comment by Illuminfti** [comment]
PR 810 closed as behind after #808. Replay on current main: https://github.com/Illuminfti/kizuki/pull/812

**Comment by Illuminfti** [comment]
PR 812 became behind after #811 merged under strict protection. Final replay on current main: https://github.com/Illuminfti/kizuki/pull/813 — head `0e1bc8c916c54c0e72d42c8b376ac7bbdc35654f`; 65 focused tests and typecheck pass; required GitHub test is running.

**Comment by Illuminfti** [comment]
Tick slice: successful `rebuild --port` with `--layer all` now flips `[ports].retrieval` and records `port_state`. Failed or partial rebuilds leave the previous default. Previous store remains until `--prune-old`.

PR: https://github.com/Illuminfti/kizuki/pull/824
Head: `cb80fc868dfd5cf2e9c941c8694fe6d6080ed979`

Tests: `bun test packages/core/test/retrieval/persist.test.ts packages/core/test/retrieval/rebuild-port-docs.test.ts packages/core/test/index.test.ts packages/core/test/migration.test.ts packages/cli/test/rebuild.test.ts packages/cli/test/help.test.ts packages/cli/test/inventory.test.ts` plus `bun run typecheck`.

Does not close this issue. Embedding-space re-embed confirmation remains unbuilt. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Tick slice: `rebuild --layer all` refuses an embedding-space change unless `--confirm` is passed, priced from doctor's measured embed-backfill throughput (`unmeasured` when none). Confirmation is checked before the engine opens. A failed vector rebuild keeps the previous generation.

PR: https://github.com/Illuminfti/kizuki/pull/825
Head: `cecbfbff2fe76209fe3ce99e08cc09c1b2393d2c`

Tests: `bun test packages/core/test/retrieval/reembed.test.ts packages/core/test/retrieval/rebuild-port-docs.test.ts packages/core/test/retrieval/persist.test.ts packages/core/test/index.test.ts packages/core/test/serve/doctor.test.ts packages/retrieval-pg/test/reembed.test.ts packages/cli/test/rebuild.test.ts packages/cli/test/help.test.ts` plus `bun run typecheck`.

Does not close this issue. Binding a live embedding port through packaged CLI rebuild remains unbuilt. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Tick slice: `rebuild --layer all` binds the configured GGUF embedding port into embedded-pg so a confirmed space change actually re-embeds. Unavailable bindings refuse instead of dropping stored vector state.

PR: https://github.com/Illuminfti/kizuki/pull/826
Head: `ee5118ed1d0e56402168220bd6d10dd764502fdc`

Tests: `bun test packages/cli/test/rebuild.test.ts packages/cli/test/help.test.ts packages/core/test/retrieval/rebuild-port-docs.test.ts` (50) plus retrieval-runtime callers and `bun run typecheck`.

Does not close this issue. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Tick slice: after a successful retrieval-port rebuild, snapshot document identities must be present before the lexical floor is rebuilt. A store that drops a snapshot document fails closed. Incremental FTS document set and golden lexical recall match a full rebuild.

PR: https://github.com/Illuminfti/kizuki/pull/827
Head: `b2879d3c2f56800e34b48d98630324d148bc6e83`

Tests: `bun test packages/core/test/retrieval` (57) plus source-grants/mutation-callers (53) and `bun run typecheck`.

Does not close this issue. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Tick slice: `rebuild --layer search|graph` rebuilds the SQLite floor without opening a configured retrieval engine. `--port` on those layers is refused before initialization.

PR: https://github.com/Illuminfti/kizuki/pull/829
Head: `fd43cd31d7dacd15540fc13ff35408bee8aef1ab`

Tests: `bun test packages/cli/test/rebuild.test.ts packages/cli/test/help.test.ts packages/core/test/retrieval/rebuild.test.ts packages/core/test/retrieval/rebuild-port-docs.test.ts` plus `bun run typecheck`.

Does not close this issue. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Tick slice: replayed PR https://github.com/Illuminfti/kizuki/pull/829 onto the current backlog branch after its CI hit an unrelated `scripts/release-download.test.ts` 5s subprocess timeout (6892 pass / 1 fail on that run; the two preceding main commits were green, file untouched by the slice).

PR: https://github.com/Illuminfti/kizuki/pull/831
Head: `489a52a048b10480b122d261c4b93f99c66ae9c8` (diff identical to #829 head `fd43cd31`)

Tests: regression test proven failing before the fix; `bun test packages/cli/test/rebuild.test.ts packages/cli/test/help.test.ts packages/core/test/retrieval/rebuild.test.ts packages/core/test/retrieval/rebuild-port-docs.test.ts` (65) plus `bun run typecheck`.

Checks: `secrets` and `workflows` pass; `test` was still pending at the end of the single 10-minute wait window, so the PR is left open unmerged per the ship-or-stop rule.

Does not close this issue. Does not claim production/go-no-go qualification.

**Comment by Illuminfti** [comment]
Worker 12 patch handoff for oracle-backlog: #103.

Concrete patch: /data/kizuki-worktrees/issue103-pandora-w12.patch
Worktree: /data/kizuki-worktrees/issue103-pandora-w12
Base: 15ecf65d (origin/main at start; touched paths unchanged on latest fetch).

Fix: track whether rebuildFromDocuments rejected independently of its rejection value. A rejection with undefined previously looked like success when the selected store already held the snapshot; it could refresh the SQLite floor and return success. Cleanup still runs before the original rejection is propagated.

Regression evidence: the undefined case failed before the fix; after the fix all 19 tests in packages/core/test/retrieval/rebuild.test.ts pass (109 assertions), bun run typecheck and git diff --check pass. Added cases cover undefined, null, false, zero and empty-string rejection values with unchanged search/graph floor snapshots.

Full bun run verify remains running; log: /data/kizuki-worktrees/issue103-pandora-w12-verify.log. No full-gate, independent-review, merge-ready or release claim. No paid model or fallback used. This is a local patch handoff, not a merged fix.

**Comment by Illuminfti** [comment]
Verification update for the Worker 12 patch at /data/kizuki-worktrees/issue103-pandora-w12.patch: the full gate was stopped after observing a 5-second tracked-network test timeout and a capability-proof producer child returning null exitCode. A broader retrieval run returned 60 pass / 2 fail; its failure details were not retained, so that run is not claimed green. The isolated rebuild file previously passed 19/19 and typecheck passed. Full-suite and independent-review clearance remain outstanding; patch handoff only, not MERGE_READY.

**Comment by Illuminfti** [comment]
Worker 7 patch handoff — oracle-backlog: #103

Concrete patch: /data/kizuki-worktrees/issue103-sebas-w7.patch
Worktree: /data/kizuki-worktrees/issue103-sebas-w7
Base: c59e700f654b650b1c87612f763ffc0f07ffbfbf

Streams event enumeration through an owned SQLite statement, finalized by using, instead of materializing an extra event-row array. Snapshot ordering and projections remain unchanged. This is a bounded streaming slice, not end-to-end streaming: document snapshots and claims are still materialized. Does not include Worker 12's rejection-value patch.

Verification: baseline sabotage fails on the event enumeration query; restored patch passes all 58 retrieval tests (267 assertions). bun run typecheck and git diff --check pass. Patch reverse-apply check passes. Full bun run verify was stopped by a 120-second budget (exit 124); no full-gate, independent-review or MERGE_READY claim. Earlier focused runs hit two default 5-second test timeouts; the final retrieval run passed without timeout changes.

Local uncommitted patch handoff only; no merge or release. Verification log: /data/kizuki-worktrees/issue103-sebas-w7-verify.log

**Comment by Illuminfti** [comment]
Worker 7 verification clarification: the full verify log also contains a failure before the 120-second cutoff: network source verification > the tracked tree has no unallowlisted network calls or stale entries exceeded its existing 5-second test deadline. Full verification is not green; this failure has not been classified against baseline. Final isolated streaming regression rerun passes. Patch remains a handoff, not MERGE_READY.

**Comment by Illuminfti** [comment]
Worker 10 slice: PR https://github.com/Illuminfti/kizuki/pull/907.

Rebuild snapshot order no longer depends on the host locale: `readRebuildSnapshot` orders by code units instead of `localeCompare`, matching SQLite collation, so selected-port `rebuildFromDocuments` input and snapshot order are host-independent.

Proof: the new ordering regression test was red on base (7792b542) and green after the fix; `bun test packages/core/test/retrieval` (58), the rebuild and rebuild-port-docs files (17), `bunx tsc --noEmit`, and `git diff --check` pass on head 882b8401718c50febd35f3074df2d4025ef5d851 (base 87e023bb).

Does not close #103. Remaining #103 slices stay open.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 10 / aura patch handoff.

Concrete patch: /data/kizuki-worktrees/issue103-aura-w10-claims-stream.patch
Worktree: /data/kizuki-worktrees/issue103-aura-w10-claim-order
Branch: worker10/103-claim-order
Base/head (uncommitted diff): 762d5610c524aff585d9bdeffc52f90e8c2e0b46
Patch SHA256: 1d2079fb904d6fdd5f7cc1a4489e4efe8f3a558d602e4c23721828c36dd2d7d2

Changes packages/core/src/retrieval/rebuild.ts to use the existing listClaims streaming filter path, avoiding the all-live SQL row array and filtering unreadable claims before collecting results. Accepted claims and document snapshots remain materialized; this is not end-to-end streaming. No public contract, dependency, network path, or authoritative state change.

Regression in packages/core/test/retrieval/rebuild.test.ts proves unchanged readable projections and omission of unreadable claims, and detects the old materializing query. It fails on restored baseline at the intended assertion and passes with the patch: 1 pass, 4 assertions. git diff --check and patch reverse-apply check pass.

Whole rebuild file latest run: 14 pass, 2 fail at existing 5-second deadlines (graph-only configured-engine refusal; golden recall). Earlier run: 13 pass, 3 deadline failures. Typecheck did not finish within the 120-second and 300-second combined command budgets; no typecheck success claimed. Full repository gate and independent review not run. No MERGE_READY, CI, merge, or release claim. Local patch handoff only. Issue was already closed; its state is unchanged. No paid model or fallback used.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 6 / pestonya patch handoff

Concrete patch: /data/kizuki-worktrees/issue103-pestonya-w6-preflight.patch
SHA256: 13a47067167d0279eae52266c7acd5244fee4232771b6d170347f9fddd890763
Worktree: /data/kizuki-worktrees/issue103-pestonya-w6-genmeta
Branch: agent/103-pestonya-w6-genmeta
Base/head (uncommitted diff): 6795cbe32d38e3741be628a670220747897184ad
Latest fetched main: 8cc591249becf04d198950f9d2cce62905739d97; neither changed path differs from the recorded base.

Moves the existing unsupported partial-layer/selected-port rejection before withVault. Invalid rebuild --layer search|graph --port ID now reports the operation error without resolving config or initializing vault state. Removes the duplicate callback check. No new CLI flag, schema, dependency, network path, or model invocation.

Changed paths:
- packages/cli/src/commands/rebuild.ts
- packages/cli/test/rebuild-preflight.test.ts

Verification:
- Baseline implementation failed the new refusal assertion for both partial layers: it reported uninitialized vault instead.
- Final isolated regression: 4 pass, 0 fail, 20 assertions. Covers both layers with absent and malformed config; no vault creation.
- bun run typecheck: exit 0 within 300 seconds.
- git diff --check and reverse patch applicability: pass.
- Broader rebuild/preflight/help run hit the 300-second command bound with per-test 5-second timeouts. The existing configured-engine, graph-only, search-only, partial-port refusal, prune-old and persistent-default cases passed before cutoff; no complete suite pass claimed.
- Separate help suite: 14 pass / 22 fail, all failures reported existing 5-second deadlines. Isolated rebuild-help case also timed out. Failure cause is not established against baseline.
- Full bun run verify: stopped at the 60-second budget during typecheck (exit 124); workflow, maestro, install and RFC checks completed. Standalone typecheck passed separately.

Logs: /data/kizuki-worktrees/issue103-pestonya-w6-preflight-typecheck.log and /data/kizuki-worktrees/issue103-pestonya-w6-preflight-verify.log.

Local patch handoff only. Not MERGE_READY. No full-suite, independent-review, CI, merge, release or participant qualification claim. Issue was already closed; state unchanged. No paid model or fallback used. This slice does not implement generation metadata despite the preparatory branch name.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 9 patch handoff

Concrete patch: /data/kizuki-worktrees/issue103-solution-w9-stream-canon.patch
SHA256: ccf8be58b5018c072303eaac99ed4e5bd20871a7ad0cb31778006779eba211f6
Worktree: /data/kizuki-worktrees/issue103-solution-w9-pool7
Branch: agent/103-worker9-stream-canon
Base/head (uncommitted diff): 8cc591249becf04d198950f9d2cce62905739d97
Latest fetched main equals that base. No PR head for this local patch.

Changes:
- packages/core/src/retrieval/rebuild.ts: enumerate canon preflight directories with opendirSync/readSync instead of allocating each entire directory through readdirSync before enforcing the existing entry bound. Close each handle in finally, including refusal paths.
- packages/core/test/retrieval/rebuild.test.ts: regression rejects materialized preflight enumeration and proves handles are closed on oversized-canon refusal.

The live consumer is rebuild's shared canon preflight for all/search/graph. Existing record/byte bounds, exclusions, linked-entry refusal and document ordering are unchanged. This is only directory-preflight streaming, not end-to-end document or claims streaming. No dependency, model call, network path, contract or authoritative-state change.

Verification:
- New regression failed on unchanged production code with the expected materialization error; log: /data/kizuki-worktrees/issue103-solution-w9-red.log.
- Initial rebuild suite: 15 pass / 1 fail, with the existing locale-independent ordering test exceeding its 5-second deadline. New regression passed. Log: /data/kizuki-worktrees/issue103-solution-w9-pool7-green.log.
- Latest bun test packages/core/test/retrieval packages/core/test/serve/extract-legacy.test.ts: 84 pass / 0 fail across 10 files, including the ordering test. Log: /data/kizuki-worktrees/issue103-solution-w9-pool7-retrieval.log.
- bun run typecheck: exit 0. Log: /data/kizuki-worktrees/issue103-solution-w9-pool7-typecheck.log.
- git diff --check and patch reverse-apply check: pass.
- Full bun run verify stopped at the explicit 120-second bound during typecheck (exit 124). Workflow, Maestro, install and RFC checks completed. Log: /data/kizuki-worktrees/issue103-solution-w9-pool7-verify.log. Full gate is not green.

Local patch handoff only. Independent review, full gate and integration remain outstanding. Not MERGE_READY; no CI, merge or release claim. Issue was already closed and its state is unchanged. No paid model or fallback used.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 4 / yuri patch handoff

Concrete patch: /data/kizuki-worktrees/issue103-yuri-w4.patch
SHA256: 72e1913f2874661f4e95e58995955e5552dc3330f265a7847b91bc4311f6c27f
Worktree: /data/kizuki-worktrees/issue103-yuri-w4
Branch: agent/103-yuri-worker4
Base/head (uncommitted diff): 02a55fccd2850cdd517bc5e0f70b51ea2bbedaeb

This reimplements the rejection-value defect already reported by Worker 12 on current main; it is not a new finding or an additional independent fix. Integrators should take one implementation, not both.

Changes:
- packages/core/src/retrieval/rebuild.ts tracks rejection separately from its value. A selected port rejecting with undefined no longer returns success and advances SQLite floor metadata. Existing settlement cleanup still precedes propagation.
- packages/core/test/retrieval/rebuild.test.ts covers undefined, null, false, zero and empty-string rejections after the synthetic store has accepted the snapshot. Search documents, search metadata, graph edges and graph metadata remain unchanged.

Verification:
- Regression before the decisive conditional change: undefined failed at expected rejected=true / received=false; the other four cases passed. The preliminary unused failure flag was already present. Log: /data/kizuki-worktrees/issue103-yuri-w4-red.log.
- bun test packages/core/test/retrieval: 63 pass, 0 fail, 296 assertions. Log: /data/kizuki-worktrees/issue103-yuri-w4-green.log.
- bun run typecheck: exit 0. Log: /data/kizuki-worktrees/issue103-yuri-w4-typecheck.log.
- git diff --check and reverse patch applicability pass.
- Full bun run verify was attempted twice: 120-second bound stopped during typecheck; 300-second bound passed typecheck and entered tests, then stopped (exit 124). The latter run also recorded two existing 5-second deadline failures: tracked network tree scan and archive inspection environment isolation. Their cause has not been classified against baseline. Log: /data/kizuki-worktrees/issue103-yuri-w4-verify-long.log. Full gate is not green.

The consumer is rebuildRetrieval's selected-port path, exercised locally with synthetic vaults. No deployed consumer receipt. No dependencies, public contracts, model calls or network paths added. Self-review found no additional changes needed; independent review is unrun. This is a local patch handoff, not MERGE_READY, CI clearance, merge or release. Issue was already closed; its state is unchanged. No paid model or fallback invoked.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 9 incremental patch handoff

Concrete patch: /data/kizuki-worktrees/issue103-w9-bounded-cleanup.patch
SHA256: 707eec71abd9d9a4636a8926140aea64a1491e9821ac3a68f33b21af2073caf4
Worktree: /data/kizuki-worktrees/issue103-solution-w9-pool7
Branch: agent/103-worker9-stream-canon
Base/head (uncommitted diff): 8cc591249becf04d198950f9d2cce62905739d97
Fetched main: bee797ea7c6a8bba0a0f88ed06cb3329952c399f; no differences from base in the three touched paths. No PR head for this local patch.

This complete patch supersedes /data/kizuki-worktrees/issue103-solution-w9-stream-canon.patch. Do not stack both. It retains that prior directory-preflight change, and adds a new production delta in rebuildUnderFence: collect at most 100 invalid document IDs directly from the remaining map, instead of allocating and filtering the whole remaining corpus before slicing it. Each cleanup batch still re-reads current authorization and revisions. Snapshot materialization remains; this is not end-to-end streaming or a measured performance claim.

The added 201-document settlement case proves three batches [100, 100, 1], exact removed identities, matching absence checks, and an empty final store. The 101-document case remains. This is behavior-preservation coverage, not a red-before-fix regression claim.

Verification in this cycle:
- bun test packages/core/test/retrieval packages/core/test/serve/extract-legacy.test.ts: 85 pass, 0 fail, 482 assertions across 10 files.
- bun run typecheck: exit 0.
- git diff --check and patch reverse-apply check: pass.
- Full bun run verify: stopped by explicit 120-second budget during typecheck, exit 124. Workflow, Maestro, install and RFC gates completed. Full gate is not green.

Logs:
/data/kizuki-worktrees/issue103-w9-cleanup-retrieval.log
/data/kizuki-worktrees/issue103-w9-cleanup-typecheck.log
/data/kizuki-worktrees/issue103-w9-cleanup-verify.log

The consumer is selected-port rebuild settlement, exercised with synthetic local vaults. No model calls, dependencies, network paths, public contracts or authoritative-state changes added. Independent review and integration remain outstanding. Local patch handoff only, not MERGE_READY, CI clearance, merge or release. Issue was already closed; state unchanged. No paid model or fallback used.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 - Worker 6 / pestonya / albedo-ua-pool4 patch handoff

Concrete patch: /data/kizuki-worktrees/issue103-pestonya-pool4-budget.patch
SHA256: 70b6c6c4a0eef58bdd8161c727d448c8b693b053bb9e1fae67615a70681ce916
Worktree: /data/kizuki-worktrees/issue103-pestonya-pool4-stream-canon
Branch: agent/103-pestonya-pool4-stream-canon
Base/head (uncommitted diff): bee797ea7c6a8bba0a0f88ed06cb3329952c399f
Fetched main still equals that base. No open PR among the 100 checked touches either changed path.

Changes:
- packages/core/src/retrieval/rebuild.ts returns the canon preflight byte count and includes it in the existing full-snapshot 64 MiB budget alongside event text and live claim bodies. Previously canon and SQLite each received a separate 64 MiB allowance. Refusal happens before loading canon or calling the selected engine.
- packages/core/test/retrieval/rebuild.test.ts uses synthetic stat sizes to exercise the aggregate boundary without allocating a large corpus, and proves no engine call or search/graph/metadata changes on refusal.

This is a bounded-memory accounting slice, not end-to-end streaming or generation metadata, despite the preparatory branch name. Partial-layer behavior and existing limits remain unchanged. The consumer is full rebuild's shared authoritative snapshot and settlement reread. No dependency, public contract, network path, model invocation or authoritative-state mutation added.

Verification:
- Initial regression against unchanged production code failed because the rebuild resolved instead of rejecting; /data/kizuki-worktrees/issue103-pestonya-pool4-budget-red.log. The fixture's overloaded stat mock and tracking assertion were subsequently corrected.
- Final bun test packages/core/test/retrieval: 66 pass, 0 fail, 308 assertions across 10 files; /data/kizuki-worktrees/issue103-pestonya-pool4-budget-retrieval.log.
- Final bun run typecheck: exit 0; /data/kizuki-worktrees/issue103-pestonya-pool4-budget-typecheck2.log.
- git diff --check and reverse patch applicability: pass.
- Full bun run verify stopped at the explicit 120-second bound during typecheck, exit 124. Workflow, Maestro, install and RFC checks completed. /data/kizuki-worktrees/issue103-pestonya-pool4-budget-verify.log. Full gate is not green.
- Earlier CLI/core combined run before the production change hit its 300-second bound while still in CLI tests, with existing 5-second test deadlines and between-test errors. No completed CLI-suite pass or baseline classification claimed.

Integration: other #103 patch handoffs touch rebuild.ts and rebuild.test.ts. This does not include or supersede their changes. In particular, preserve Worker 9's directory streaming when reconciling boundCanon, and return its accumulated bytes after its loop; preserve the other streaming, cleanup and rejection-value fixes separately. No other lane was edited. Self-review found no further change needed; independent review and full gate remain outstanding.

Local patch handoff only. Not MERGE_READY, CI clearance, merge or release. No participant qualification or credit claim. Issue state unchanged. No paid model or fallback used.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 — Worker 11 / demiurge / ox-alpha-test code handoff

Open draft PR: https://github.com/Illuminfti/kizuki/pull/953 ("Snapshot FTS rebuild documents before a producer reuses its object").
Branch: agent/103-demiurge-w11-staging (own new branch + worktree /data/kizuki-worktrees/issue103-demiurge-w11).
Exact base: bee797ea7c6a8bba0a0f88ed06cb3329952c399f (= origin/main at cycle start; re-fetched equal immediately before commit and push). Head: 694b5e0d5b2efe4f533fb7bfacdd79ed4f05206f.

Incremental patch: /data/kizuki-worktrees/issue103-demiurge-w11-fts-doc-snapshot.patch
SHA256: 0d0e0b26c6e67a0f0344b7e45ddcea299615f0935489fb93733024d41712d1e2

Changes two files:
- packages/core/src/retrieval/fts5.ts — rebuildFromDocuments now stages structuredClone(validateRetrievalDoc(doc)) so a producer reusing its document object between yields cannot overwrite an earlier staged document (the caller in packages/core/src/retrieval/rebuild.ts already clones its snapshot; iterable inputs from other callers are not required to). Previously the mutated object was pushed to the SQLite store and the first document was silently lost.
- packages/core/test/retrieval/fts5.test.ts — regression: one object yielded twice with mutation between yields; asserts both identities are present after rebuild, the second projection wins, "mutatedafteryield" text is absent, and stored subjects/provenance for the first id match its first-yield values.

Verification (Bun 1.3.14, Linux x64):
- Red: the regression failed on unchanged production code — verifyAbsent found only page:replacement, page:grace lost; /data/kizuki-worktrees/issue103-demiurge-w11-red.log.
- Green focused: bun test packages/core/test/retrieval/fts5.test.ts → 15 pass, 0 fail, 55 assertions; /data/kizuki-worktrees/issue103-demiurge-w11-fts-green.log.
- packages/core/test/retrieval: 65 pass / 1 fail; the only failure is the known existing 5-second deadline timeout on "selected port reports its validated corpus including readable claims separately from floor rows" (6.2s; file untouched by this slice); an earlier identical run failed on a missing node_modules dependency before bun install --frozen-lockfile. Logs: /data/kizuki-worktrees/issue103-demiurge-w11-retrieval.log (pre-install) and /data/kizuki-worktrees/issue103-demiurge-w11-retrieval-green.log.
- bun run typecheck: exit 0 within a 300-second bound; /data/kizuki-worktrees/issue103-demiurge-w11-typecheck.log.
- bun run verify with an explicit 120-second bound: required-commands, required-helpers, full-history, workflows, maestro, install and rfc-tests gates passed; the run was stopped by the bound during typecheck (exit 124). This is bounded verification, not a full-gate pass; /data/kizuki-worktrees/issue103-demiurge-w11-verify.log.
- Patch checks: forward apply to a reconstructed baseline copy, byte equality with the worktree, and reverse apply all pass. git diff --check clean.

Integration: other #103 patch handoffs touch rebuild.ts and rebuild.test.ts; this slice is independent of them (fts5.ts + fts5.test.ts only) and does not include or supersede their changes. Core-side rebuild snapshot cloning already exists on main, so no conflict is expected.

Not MERGE_READY: independent review outstanding; the full repository gate was not completed; no CI, merge, or release claim. Issue #103 was already closed before this cycle; its state is unchanged, and this slice does not close it. No paid model or fallback used.

**Comment by Illuminfti** [comment]
oracle-backlog: #103 nous-n18 — deterministic SQLite FTS rebuild order

Concrete patch: /data/kizuki-worktrees/ua-103-n18-order.patch
SHA256: 95df0a058b3556eb76be028b41a048a41646cc43748efac94410d1fb05ed6a0d
Worktree: /data/kizuki-worktrees/ua-103-n18
Branch: agent/103-nous-n18-stream-floor
Base/HEAD: bee797ea7c6a8bba0a0f88ed06cb3329952c399f (freshly fetched origin/main matches). Changes remain an uncommitted diff.

Changes:
- packages/core/src/search/indexer.ts: projectSearchDocs now inserts FTS rows from companion documents in explicit binary doc_id order. SQLite scan direction no longer changes rebuilt FTS rowid assignment.
- packages/core/test/search/search.test.ts: regression rebuilds the same ledger with reverse_unordered_selects enabled and checks identical rowid/document mapping plus retained search results.

This is a narrow determinism fix in the SQLite floor, not end-to-end streaming, generation switching, or a claim of complete #103 implementation. Public contracts, authorization, document contents, and transaction boundaries are unchanged. EXPLAIN QUERY PLAN uses the existing unique doc_id index; no temporary sorting structure was reported. No dependency or model call added.

Collision check: no open PR among the 100 requested touches either changed file. #103 PR #953 changes retrieval/fts5.ts and its test; this patch does not touch that lane or the retrieval/rebuild.ts handoffs.

Verification:
- New regression passes: 1 pass, 0 fail, 3 assertions. Temporarily removing the production change makes it fail at the row mapping assertion; the fix was restored and rerun.
- bun test packages/core/test/derived packages/core/test/retrieval packages/core/test/search: 138 pass, 1 fail, 524 assertions across 15 files. Failure: existing 'rebuildSearch stays linear for thousands of ledger rows' timing bound. The timing case also failed in three isolated runs on unchanged base. No performance improvement or complete suite pass claimed.
- bun run typecheck: exit 0 after dependency installation. Initial pre-install attempt failed with missing Bun type definitions.
- timeout 120 bun run verify: exit 124 during typecheck; preceding required-command/helper/history, workflow, Maestro, install, and RFC gates passed. Full gate not completed.
- git diff --check and reverse patch applicability: pass.

Logs: /data/kizuki-worktrees/ua-103-n18-tests.log, /data/kizuki-worktrees/ua-103-n18-typecheck.log, /data/kizuki-worktrees/ua-103-n18-verify.log.

Self-review: one SQL ordering clause, existing index, unchanged projection policy and rollback boundary. Independent review and integration remain outstanding. Local patch handoff only, not MERGE_READY. No CI, merge, release, or participant-credit claim. Issue was already closed; state unchanged. No Cap restock, paid model, or fallback used.
