### ISSUE TITLE
World Model 01: RFC 0004 reconciliation over RFC 0003 rich-subject foundation

### ISSUE THREAD

**Issue by Illuminfti** [Illuminfti/kizuki#481]
Parent: #480. Execution epic: #497. Related situation design: #476. Program document originated in #498; check its actual merge state rather than assuming it is on main.

## Coordination correction, 5 September 2026
The original ticket requested a second RFC numbered 0003. Astra's coordination comments on this issue establish that `rfcs/0003-rich-subject-foundation.md` is already proposed in #479 under #403/#472; the broader world-model proposal is reserved as **RFC 0004**. Preserve that history and reservation. Do not create another RFC0003, duplicate claim/perspective/temporal/identity stores, or resume the paused durable-rich lane #500 by implication.

Root Astra owns the bounded design reconciliation described in the existing comments. This roadmap refinement neither takes over that lane nor converts an unmerged RFC into binding law. Recheck live heads, comments and reviews before working.

## Mission
Specify the persistent personal world model against the current implementation and shared rich-subject foundation before incompatible implementation. Reuse existing claims, source policies, identity, correction, receipts, storage, retrieval and serving. Identify the precise additions and amendments rather than treating the broad vision as a replacement architecture.

## Required decisions
- Whether each semantic record is authoritative, claim-backed or derived; how it reconciles with claims and remains exportable, restorable, correctable and purgeable.
- Exact Observation, KnowledgeNode, typed Relation, EvidenceRef, StateTransition, perspective and world-view contracts; source record vs real event vs observation vs semantic object identity.
- Small versioned node/relation registry, allowed endpoint types, cardinality, namespaces, migration and extension policy. No arbitrary model-invented ontology.
- Valid time vs recorded time, late evidence, retractions, historical views, conflicting perspectives and revision consistency.
- Evidence lineage and dependent copies, source coverage, permitted uses, unknown/stale/unavailable states and higher-order invalidation.
- Owner correction, supersession, source deletion, revocation and physical purge through the existing single writer and recovery protocol.
- Principal/scope/purpose/policy-bound view tokens and diffs. A global revision must not leak restricted activity; a view token is not a lock on external reality.
- Conservative learning/demonstration semantics. Exposure, assisted work, independent performance and self-report remain different evidence classes; no compulsory mastery ladder or fabricated precision.
- Keep evidence strength, task usefulness, applicability and freshness separate. Repeated retrieval must not increase truth confidence.
- Capture, bounded consolidation (#503), current-state reads and optional analysis have distinct cost/latency/failure contracts. Correction is not delayed behind consolidation.
- Multi-resolution World Slices (#489): essential task context, current situation, evidence drill-down, explicit blind spots and honest budget overflow.
- Bounded graph/index queries, model budgets, liveness and schema/rebuild rules within the existing runtime/storage boundaries.
- One semantic contract across actual UX/DX/AX projections, stable error/retry behavior and backward compatibility with existing context/CLI/MCP consumers.

## Required artifacts
1. An explicit compatibility/amendment table for binding RFC 0002, proposed rich-subject RFC 0003, #472, #476 and the new world-model proposal. Separate binding rules, accepted owner direction, proposed semantics and shipped behavior.
2. Query-driven schema alternatives with integrity/index/cost rationale; do not choose EAV or one table per noun by reflex.
3. Worked examples: person with conflicting reports, late role change, Concept and open Question, two independent commitments, correction impact, source revocation, scoped World Slice and historical replay.
4. Interface ownership and dependency map. Shared outcome-evidence contracts may precede #492's feedback loop; avoid a #487/#489/#492 dependency cycle.
5. Start #496 fixtures immediately. First semantic vertical slice remains Concept (#484), followed by wider situations; #502 Stage A can prove current-client continuity independently of the full world model.
6. An adoption decision record for any proposed dependency: exact source revision/license/notices, bounded workload, baseline, maintenance cost, local custody/egress/purge compatibility. Default to borrowing patterns and tests, not entire competing stacks.

## Research pointers
The supplied competitive brief motivates [Honcho perspective separation](https://honcho.dev/docs/v3/documentation/core-concepts/representation), [Graphiti temporal semantics](https://www.getzep.com/platform/graphiti/), [Cognee schema grounding](https://www.cognee.ai/best-memory-framework-for-custom-representation) and [Hindsight consolidation](https://hindsight.vectorize.io/). Revalidate current primary sources during implementation. These links are not license clearance or proof of superior performance.

## Do not
Do not add public commands, MCP tools, incompatible migrations, a new authority store, a general-purpose agent loop, a new canon write path, or README capability claims ahead of accepted contracts and implementation proof. Canon is a human-readable projection through its writer, never generated from a client World Slice. Preserve the current release authority in #403 and scoped lane restrictions.

## Acceptance
The reviewed RFC names every reused/new contract, demonstrates all examples and denial paths, and resolves the collision with RFC0003 without overwriting another agent's work. Documentation links and existing verification must pass at the exact head. This ticket's completion is design acceptance only, not release or broader-world-model completion.

**Comment by Illuminfti** [comment]
Coordination with the active #403 / #472 foundation lane: draft PR #479 already contains `rfcs/0003-rich-subject-foundation.md` and the reviewed pure rich-claim, perspective, occurrence and evidence contracts. Durable rich claims (B1b), followed by their admission/backup/serving composition (B1c–d), are actively owned in the same campaign and remain unmerged.

Please reconcile this packet with that foundation before creating another RFC numbered 0003 or a parallel claim/perspective/temporal/identity store. The world-model RFC can build on those contracts and must still resolve its additional observations, world revisions, learning state and LifeOS ownership boundaries explicitly. The current rich lane is not acceptance of the broader world-model roadmap.

The foundation is repairing nine full-suite failures (five roots); its source review does not establish merge or release acceptance. This note reserves no new public API and does not expand the current B1b implementation packet.

**Comment by Illuminfti** [comment]
Owner steering reconciled with the existing #403 / #472 campaign. All feature authors have checkpointed safely. Root now owns this bounded design reconciliation; durable-rich schema work remains paused in draft #500 at 1d106e2. The immediate execution step is finishing the already near-complete foundation #479, then the RFC before any incompatible schema work resumes.

RFC0003 is already the proposed rich-subject/shared-support foundation in #479. I will preserve its history and use **RFC0004** for the wider world-model proposal, with an explicit compatibility/amendment table rather than a second claim, perspective or identity store. This is a design reservation, not a schema/API acceptance.

The new RFC will preserve frozen ingress, claim authority, SQLite/Markdown, the single receipted writer, owner correction/undo, the model-free floor and source/grant enforcement. It must concretely resolve observation vs source-record vs real-event vs semantic-object identity, time/history, independent support, erasure, principal/scope/policy-bound views and conservative non-compulsory learning evidence. Canon is a durable projection through its existing writer; permitted model-free reads can use evidence/claims/canon directly, and canon is never generated from a client World Slice.

Delivery order is first Concept after the shared contracts, with #496 privacy/lifecycle/parity/resource fixtures from that first slice. #476's Situation delivery order is superseded by the owner's later Concept-first steering while its UX/DX/AX product law remains. Shared outcome-evidence semantics do not depend on implementing the full #492 loop, preventing a #487/#489/#492 cycle. No new public capability or broader-world-model completion is claimed.

**Comment by Illuminfti** [comment]
Owned RFC0004 checkpoint is preserved in draft PR505 at `c7e53e14a9c8434dd812443129f9d93967a18c98`, on base `8f87c7d368227534fbba2f16b7863cc03c1178d6`. Status remains Proposed. Independent first-draft review found seven contract gaps: all-envelope global policy leakage, Core recorded time, physical-erasure/undo receipt transitions, full typed wire identifiers/qualifiers, allocation-receipt tombstones, complete relational ownership DDL and bounded view-token storage. Root is repairing them before schema work resumes; no accepted architecture claim.

First [CI33995417363](https://github.com/Illuminfti/kizuki/actions/runs/33995417363) passed3977 tests/3 skips/0 failures but verify correctly failed on five root-added absolute issue links containing the forbidden owner identifier. Working repair removes those links; no verification rule or history is rewritten. Native artifact steps did not run on this failed commit.

Foundation PR479 and enrollment PR501 are merged separately; canonical runtime remains unchanged. PR500 stays paused pending the accepted shared lifecycle. The synthetic Concept fixture/oracle is being reviewed from day one under #496. Next receipt will pin the repaired RFC, complete storage design, independent review and exact CI; draft CI alone cannot accept the RFC or grant a migration.

**Comment by Illuminfti** [comment]
Material checkpoint: draft #505 is now preserved and remote-verified at `30a70ef2719dc7d8c1f71b80d0e70be203bc1f29`, based on current main `ad7ecca9902a97ac40fb8b28438df56c6d27a54e`. The six-file checkpoint includes the relational/codec appendix, repaired synthetic fixtures and reproducible offline design/SQL validators. Both validators, strict standalone TypeScript, secrets, diff, links and TypeScript-fence syntax pass on this head; full CI34006556304 is running.

The preceding `7b726d96` checkpoint completed full CI plus native package/artifact checks, but that older pass does not qualify current bytes. Independent reviews have driven repairs to admission assessment identity, read-to-correction refs, the first Concept route, typed mutation objects, raw subject versus event attribution, and token expiry semantics.

Two explicit blocking design findings remain under repair: trusted non-content origin for retained terminal IDs (legacy claim/canon/purge paths can accept caller-selected IDs), and exact pending store/work proof binding. No schema implementation resumes or RFC adoption/merge is claimed. The additional authenticated current-Core subject-grant baseline is posted separately on #496; it is not world-view or physical-erasure acceptance.

**Comment by Illuminfti** [comment]
Reviewed design checkpoint: draft PR505 is local/remote verified at `03a84ab8d8ba30a8863068dfa17cbc7d41b83733`, base `ad7ecca9902a97ac40fb8b28438df56c6d27a54e`. The six-file proposal now has independent PASS on both specification/security and change-quality/regression axes with no open P1/P2. Final review closed the empty-success edge: planned/required store membership is nonempty, completion contains the exact coordinator and children, and fresh absence requires an actual new audit.

[Exact-head CI34009768614](https://github.com/Illuminfti/kizuki/actions/runs/34009768614) succeeded: 3988 pass, 3 skip, 0 fail; VERIFY_OK, native smoke/artifact proof, secrets, workflows and diff integrity. Both pinned offline validators and strict TypeScript pass independently; those validators test synthetic design/SQL constraints, not production migration, erasure, restore or world-view behavior.

The proposal makes immutable ID-origin eligibility, exact durable work/proof binding, interrupted/serial canon recovery, scoped v2 refusal and compatibility consequences explicit. It preserves frozen ingress, one canon writer and current authority ordering. Existing a96c5f4 evaluation receipts remain frozen comparisons, not a new-main execution claim.

PR505 remains Proposed/draft awaiting an explicit adoption decision. PR500 remains paused; no schema/API implementation, runtime cutover or release is claimed. Root is continuing the separately bounded current-core synthetic two-client test under #502; it does not implement this RFC or qualify whole Stage A.

**Comment by Illuminfti** [comment]
Live reconciliation at 07:30 UTC on 6 September: another actor merged PR505 as `432e361e70cdee9eba7c51cb20aca851690a7cfc`; its reviewed head is still `03a84ab8d8ba30a8863068dfa17cbc7d41b83733`. Current main is `17a27199728db8effed3d5cc526abef7c067c6f5`, including separately merged PR504 operating guidance, PR509 synthetic continuity and PR427/426 canon/staging hardening.

The RFC and storage appendix still explicitly state Proposed / not binding / not implemented. CURRENT, decision-log and RFC0002 are unchanged. Bounded independent source reconciliation found no binding adoption amendment. Therefore the proposal is now present on main, while incompatible schema/API implementation remains blocked on explicit RFC adoption; PR500 stays paused. No design-validator or earlier draft-CI receipt is upgraded into runtime proof.

The enrollment packet in draft PR510 reserves ledger17 for its independently scoped local custody table. Any later accepted world-model migration must reconcile the then-current version rather than reuse the proposed LedgerEventIdentityV17 name as shipped schema authority. Root is finishing that bounded foundation and its current-main integration tests; canonical runtime remains unchanged. This corrects the earlier draft/unmerged inventory without claiming world-model implementation or release acceptance.

**Comment by Illuminfti** [comment]
Migration reservation update after live main advanced to `03a4033bbcbd8c7deb8fd6e2f0606a14c984c778`: merged PR428 now owns shipped ledger17. Root-owned draft PR510 has deliberately composed that migration and uses **ledger18** for local enrollment custody at verified remote `ea25d5e8860efd3b3c3f4e0a9d83f75854618a2b`. Its full review/CI remains pending; [sanitized checkpoint](https://github.com/Illuminfti/kizuki/issues/502#issuecomment-5557936906).

This supersedes the earlier17 reservation in this discussion. Paused PR500 must check the then-current next migration when its separate rich contract is adopted. RFC0004 remains explicitly Proposed after its merge; no binding world schema or runtime acceptance is inferred.

**Comment by Illuminfti** [comment]
## Cue reconciliation item — Oracle reviewed 13 September 2026

The clean-room Cue review found one contract ambiguity that must be resolved before #491 implementation.

D10 and RFC 0002 prohibit an owner review queue or approval step for claim admission and autonomous canon writing. #491 now needs `approve`, `defer`, `dismiss` and `withdraw` for bounded proposed external effects.

Recommended clarification:

- D10 remains unchanged for evidence, claims, interpretation, canon, correction and undo. Cue never gates those paths.
- A Cue decision is an append-only record of the owner's exact external-effect intent. It is not source permission, a Kizuki execution grant or proof of completion.
- The separate external runtime must still hold and revalidate its own effect authority, target, audience, cost limits, current Kizuki basis and prior attempt immediately before acting.
- Material changes invalidate execution eligibility and require a new decision. Presentation-only changes do not.
- Kizuki records candidate, decision, intent, report and independently observed outcome separately. It hosts no agent and exposes no general execute endpoint.

Record this distinction in the binding decision/RFC layer before adding Cue schema or public API. This comment requests reconciliation; it does not adopt RFC 0004, amend D10, authorize a migration or claim implementation.

**Comment by Illuminfti** [comment]
Slice: PR https://github.com/Illuminfti/kizuki/pull/745

RFC 0002 now records that Cue decisions never gate evidence, claims, interpretation, canon, correction, or undo. D10 is unchanged. RFC 0004 stays proposed.

Tests: `bun test rfcs/fixtures/cue-d10-reconciliation.test.ts scripts/verify-rfc-tests.test.ts`, `bun scripts/verify-rfc-tests.ts`, `bun run typecheck`

Refs #481; does not close the issue.
